### ISSUE TITLE
Windows: Build Failure (DevToys.Business)

### ISSUE THREAD

**Issue by CoreyHayward** [DevToys-app/DevToys#1167]
### Current behavior

Currently attempting to build and run the `DevToys.Windows` project in VS 2022 but getting the following error when attempting to build:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0016	Could not write to output file 'D:\source\CoreyHayward\DevToys\obj\AnyCPU\DevToys.Business\Debug\net8.0\generated\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator\DevToys.Business.ViewModels.ToolPageViewModel.ToggleSelectedMenuItemFavorite.g.cs' -- 'Could not find a part of the path 'D:\source\CoreyHayward\DevToys\obj\AnyCPU\DevToys.Business\Debug\net8.0\generated\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator\DevToys.Business.ViewModels.ToolPageViewModel.ToggleSelectedMenuItemFavorite.g.cs'.'	DevToys.Business (net8.0)	D:\source\CoreyHayward\DevToys\src\app\dev\DevToys.Business\CSC	1		
```

I have followed the steps in the [Contributing.MD](https://github.com/DevToys-app/DevToys/blob/main/CONTRIBUTING.md) guide

### How to reproduce it (as minimally and precisely as possible)

1. Clone the repo.
2. Run `.\init.ps1`
3. Open `DevToys-Windows.sln` (Visual Studio 2022)
4. Build `DevToys.Windows`

### Expected behavior

Builds correctly

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/72159232/c1d99929-0d04-4d86-b408-f4abd2530c7d)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Commit: 79c33ce3f6bfe90f737e02d7b5b2adfe9accbc22

**Comment by veler** [comment]
Hi,
I suspect you encounter this issue because your Windows doesn't have LongPath enabled. By default, Windows paths are limited to 255 characters, and the one you shared is longer than that.

It's not the first time someone encounter a similar issue. I just made a few changes to give a heads up when building and when running `init.ps1`.

![image](https://github.com/DevToys-app/DevToys/assets/3747805/1ceb959d-4b53-4d1d-9eac-10ec85c6e9e9)

![image](https://github.com/DevToys-app/DevToys/assets/3747805/2468dcb6-a102-4f79-9d0f-28f7258938b0)

Here is the PR: #1168

**Comment by CoreyHayward** [comment]
@veler Yep, enabling long paths has fixed it! thanks very much!
