### ISSUE TITLE
Windows 11 misaligned title bar color

### ISSUE THREAD

**Issue by veler** [DevToys-app/DevToys#1228]
### Current behavior

The color on title bar is misaligned. It should be invisible (non colorized):
![image](https://github.com/DevToys-app/DevToys/assets/3747805/e0a5b02c-b190-4106-b137-496bbd496ca9)

### Expected behavior

The colorized title bar should be smaller.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0.1

**Comment by veler** [comment]
I reproduce the same issue in WPF Gallery App interestingly.

![image](https://github.com/DevToys-app/DevToys/assets/3747805/0bd5c657-7688-4939-8a12-a8b52f307e90)

**Comment by 0x5bfa** [comment]
Fyi, DevHome seemed to had this issue.

https://raw.githubusercontent.com/microsoft/devhomegithubextension/main/build/store/canary/media/ja-JP/github-setup.png

![image](https://github.com/DevToys-app/DevToys/assets/62196528/da58e2f4-571a-4c66-a84c-48ed969f46dc)

Is this some sort of issue with WinUI?

**Comment by niyari** [comment]
WIP

**Comment by veler** [comment]
Devtoys window is in WPF, so my guess is that it's a wpf specific problem, as your screenshots point it.

@niyari , did you find anything yet? I'm really struggling with this one.

**Comment by niyari** [comment]
I found that this was caused by the background color of the WPF content and WebView being set to transparent by default.
![03](https://github.com/DevToys-app/DevToys/assets/2970321/6b9b3581-88e9-48e0-a6af-5a8db32d2c37)

Specifying a background color in the Grid or webview tags in MainWindow.xaml or in the HTML content (e.g. body) in DevToys hides the WPF title bar, giving it a more natural appearance.
![image](https://github.com/DevToys-app/DevToys/assets/2970321/aa3168f9-769b-4e2e-8dd6-839a570a4a80)

The easiest fix is ​​to make the title bar color a constant using CSS.
