### ISSUE TITLE
Unicode analyser/inspector

### ISSUE THREAD

**Issue by circles-png** [DevToys-app/DevToys#706]
### Solution/Idea

Something like this:
https://www.fontspace.com/unicode/analyzer

where a user can input some text, and see the characters and hex

### Alternatives

https://www.fontspace.com/unicode/analyzer

`charinfo` command in Python Discord

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Unicode inspection/analysing | Must |
| Hex editor/inspector for this | Could |

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by clauseggers** [comment]
I thought I might tag along my requests as they are closely related to yours. The ‘Unicode analyzer’ as in the link above has limited usefulness.

What is needed is a tool that goes all the way down to HEX, showing and converting between Unicode Normalisation C and D forms: http://unicode.org/reports/tr15/

The ‘Apfelstrudel’ app does this, please have a look: https://eclecticlight.co/text-utilities-nalaprop-dystextia-and-others/

This work has of course been done before, eg. in the Textmate app: https://github.com/textmate/unicode.tmbundle

Importance: All these forms are essential to identify and convert between, because different forms are used on different computer systems, in filesystems &c.

**Comment by Cito** [comment]
Another similar tool to draw inspiration from: https://apps.timwhitlock.info/unicode/inspect

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
